### ISSUE TITLE
Final redirect not happening

### ISSUE THREAD

**Issue by MalForTheWin** [cmcgee93/wp-login-with-twitch#2]
### Expected Functionality 
Redirect URL returns new signups using Twitch to my website, passes correct parameters through JSON, sets up new user, and redirects them to the page chosen for follower or subscriber as selected in the API Settings tab of the plugin.

### Actual Functionality
Redirect URL returns new signups using Twitch to my website, passes correct parameters through JSON, sets up new user, **_BUT DOES NOT redirect them to the page chosen for follower or subscriber as selected in the API Settings tab of the plugin_**.
Return & redirect process stops at the following URL:
http://www.malforthewin.com/wp-json/login-with-twitch/v1/register/?code=3rq6j2hep99dgodem7a7belvcmp8pw&scope=user%3Aread%3Aemail+channel%3Aread%3Asubscriptions
Sometimes it is a blank page, sometimes it reads, "API failure, invalid response"

### Steps to Reproduce Issue 
Happens every time, with any account I've had test the plugin. Just not redirecting all the way for some reason.

**Comment by cmcgee93** [comment]
Hey, 

I'll take a look at this when I get chance and get back to you. Hopefully a little bit later on today. 

Thanks for mentioning it!
 
Chris

**Comment by cmcgee93** [comment]
Hey MaalForTheWin, 

Sorry it's took a while to get back to you on this. I've now fixed this issue 🤞  everything now works as expected. Please make sure to update to the latest version in repo. 

Please let me know if there are any other issues or if there are any other features you would like to see and I will take a look at updating the plugin further.

[Changes](https://github.com/cmcgee93/wp-login-with-twitch/commit/1448483b385d86345ab70db29479f933c4bc1f86)
